export const LOAD_APP_DATA = 'LOAD_APP_DATA';
export const LOAD_APP_DATA_START = 'LOAD_APP_DATA_START';
export const LOAD_APP_DATA_SUCCESS = 'LOAD_APP_DATA_SUCCESS';
export const LOAD_APP_DATA_FAIL = 'LOAD_APP_DATA_FAIL';

export const SET_PRAYERS = 'SET_PRAYERS';
export const GET_PRAYERS = 'GET_PRAYERS';

export const SET_FLASHCARDS = 'SET_FLASHCARDS';
export const GET_FLASHCARDS = 'GET_FLASHCARDS';